// app/layout.tsx or app/rootLayout.tsx
import type { Metadata } from "next";
import "./globals.css";
import StoreProvider from './StoreProvider'
import ClientAuthLoader from "./ClientAuthLoader";
import { Toaster } from "@/components/ui/sonner";


export const metadata: Metadata = {
  title: "Project Management",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) 


{
  return (
    <html lang="en">
      <body>
        <StoreProvider>
          <ClientAuthLoader />{children}</StoreProvider>
          <Toaster/>
          </body>
    </html>
  );
}
